version: '3.9'

services:
  db:
    image: postgres:16.1-alpine3.19
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cyberpunk_inventory

  web:
    build: .
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: cyberpunk_inventory
      DB_USER: postgres
      DB_PASSWORD: postgres
