"""Update User model

Revision ID: 7d8089c86e53
Revises: df81766fbef4
Create Date: 2024-08-19 10:35:06.687861

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d8089c86e53"
down_revision: Union[str, None] = "df81766fbef4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("username", sa.String(), nullable=True))
    op.drop_constraint("user_email_key", "user", type_="unique")
    op.create_unique_constraint(None, "user", ["username"])
    op.drop_column("user", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "user", type_="unique")
    op.create_unique_constraint("user_email_key", "user", ["email"])
    op.drop_column("user", "username")
    # ### end Alembic commands ###
