"""Update User model

Revision ID: df81766fbef4
Revises: 37b27a3786e5
Create Date: 2024-08-19 09:49:19.135132

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df81766fbef4"
down_revision: Union[str, None] = "37b27a3786e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("hashed_password", sa.String(), nullable=True))
    op.drop_constraint("user_id_key", "user", type_="unique")
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.drop_column("user", "is_active")
    op.drop_column("user", "password")
    op.drop_column("user", "is_admin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("is_admin", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user", sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.create_unique_constraint("user_id_key", "user", ["id"])
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###
