"""Create USer model

Revision ID: e2587dcb5e38
Revises: 8b0bb501918d
Create Date: 2024-08-18 22:19:50.253467

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2587dcb5e38"
down_revision: Union[str, None] = "8b0bb501918d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("is_admin", sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, "user", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "is_admin")
    op.drop_column("user", "is_active")
    # ### end Alembic commands ###
